# Generated by Django 5.0.1 on 2024-02-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_links_visualizacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='visualizacoes',
        ),
    ]
