# Generated by Django 5.0.1 on 2024-02-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_links_isualizacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='isualizacoes',
        ),
    ]
