# Generated by Django 5.0.1 on 2024-02-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_links_isualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
