# Generated by Django 5.0.1 on 2024-02-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_links_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='origem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
