# Generated by Django 5.0.1 on 2024-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_links_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
