# Generated by Django 5.0.1 on 2024-02-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_links_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='avatar',
        ),
    ]
