# Generated by Django 5.0.1 on 2024-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_links_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='avatar_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
